### ISSUE TITLE
Programing V4.0 with Binary results in NFC test fail.

### ISSUE THREAD

**Issue by coryjfowler** [NXPHoverGames/RDDRONE-BMS772#6]
I downloaded the "nuttx.bin," flashed it using the instructions, and I get a solid red LED with the below on the serial console.  It will be a few hours before I can attempt to build from source myself.

```
SELF-TEST NFC: START
nfc ERROR: config reg has the wrong value = 8, 40 should be 8, 46
main ERROR: failed to initialize nfc! code -1
SELF-TEST NFC: FAIL
```

**Comment by cisvanmierlo** [comment]
Hi @coryjfowler, 

I'm sorry to hear that you run into a problem with the BMS board.
Could you help us to find this problem by stating which revision BMS you have?
This can be found on the other side of the programming header in the copper, it will state for example "Rev D".

Since there seems to be a problem with NFC, would it be possible to state the marking on the chip U5 at the bottom?
Keep in mind that these are very small and you'll probably need a magnifying glass to see them.

**Comment by coryjfowler** [comment]
I thought V4.0 was the revision, but it does have a "REV D" in the bottom copper layer.
There are three lines on U5, the top line starts with a small circle or logo centered with the other characters.  
` A21
1308
D101`

**Comment by igalloway** [comment]
Hello @coryjfowler 
FYI - this issue is being actively investigated.

**Comment by cisvanmierlo** [comment]
A bugfix has been uploaded and this should resolve the issue. 

Thank you very much for addressing this problem!
